[build]
  # Mudamos para a pasta raiz "functions"
  functions = "functions"
  # Adicionamos um comando falso para for√ßar o Netlify a "acordar"
  command = "echo 'Instalando Python...'"

[[redirects]]
  from = "/feed/*"
  to = "/.netlify/functions/converter?hash=:splat"
  status = 200
