[build]
  # Para JS, o Netlify detecta o package.json e roda "npm install" sozinho.
  # NÃ£o precisamos definir nada manual aqui!

[[redirects]]
  from = "/feed/*"
  to = "/.netlify/functions/feed?hash=:splat"
  status = 200
