[build]
  # O Netlify já sabe procurar em netlify/functions por padrão
  # Não precisamos definir nada aqui

[[redirects]]
  from = "/feed/*"
  to = "/.netlify/functions/converter?hash=:splat"
  status = 200
