[build]
  # O Netlify vai procurar na pasta padr√£o (netlify/functions) automaticamente
  # O comando abaixo garante que ele instale o requests
  command = "pip install requests"

[[redirects]]
  from = "/feed/*"
  to = "/.netlify/functions/feed?hash=:splat"
  status = 200
