[build]
  # Mantemos backend por enquanto, mas o comando abaixo vai nos contar a verdade
  functions = "backend"
  command = "echo '--- INICIO DA LISTAGEM ---' && ls -R && echo '--- FIM DA LISTAGEM ---'"

[[redirects]]
  from = "/feed/*"
  to = "/.netlify/functions/feed?hash=:splat"
  status = 200
