[build]
  # Removemos a linha 'functions = ...'. Deixe o Netlify usar o padr√£o dele.
  command = "pip install requests"

[[redirects]]
  from = "/feed/*"
  to = "/.netlify/functions/feed?hash=:splat"
  status = 200
